### ISSUE TITLE
Tag filter

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#26]
Richiesto dal nostro Kuroki senpai, una possibilità di nascondere certi tag, tipo per rendere il sito SFW.

Si potrebbe fare con dei campi nei cookie, suppongo.

**Comment by Hamcha** [comment]
Sposto in bassa priorita' per il momento

**Comment by silverweed** [comment]
È stata richiesta la funzione di "Hide thread"; 
valutare se è possibile unire queste due cose, o tramite cookie (pro: possiamo filtrare direttamente a server side e quindi a livello handler non far uscire proprio i thread nascosti, contro: > cookie) o tramite localStorage (pro: niente cookie, la struttura client-side c'è già, anche se da fixare, per la safe mode, contro: dobbiamo filtrare per forza client-side, quindi spoilerare i thread).

**Comment by silverweed** [comment]
Uh, si può avere solo 1 assignee alla volta?

**Comment by Hamcha** [comment]
È proprio un bel pasticcio.
Credo che spoilerare sia come non fare nulla, visto che alla fine non diventa molto utile.. però se già il safe mode clientside da problemi, l'hiding non mi aspetto sia così facile da far andare.

Credo comunque che valga la pena provare a sistemare tutto e farlo server-side.

**Comment by silverweed** [comment]
Ok, quindi voti per il cookie giusto? Se vuoi ci penso io, ho già idea di come farlo...solo che oggi sono via tutto pomeriggio, quindi se riesco a farlo stasera bene, se no slitta a domani.

**Comment by Hamcha** [comment]
Boh, io oggi forse mi do a Dvx, quindi anche per me slitta a domani

**Comment by silverweed** [comment]
Vedi #63

**Comment by Hamcha** [comment]
#63 mergata, chiudo fino a nuovo aggiornamento
