### ISSUE TITLE
Minor edits

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#28]
- [X] ~~Favicon~~ 949fed1
- [X] ~~Licenza~~ e9b5c80
- [X] ~~Fix icone~~
- [X] ~~Cambiare il separatore tag da , (virgola) a # (per evitare ulteriore confusione)~~ e5acf78
- [x] Sistemare il purpletext nei post legacy (togliendo l'hack su coffeescript)
- [x] Controlla derpibooru su WP

**Comment by silverweed** [comment]
Aggiungo che derpibooru è rotto anche su Android.

**Comment by silverweed** [comment]
Reminder a me stesso: controllare in posts.coffee ([qui](https://github.com/Hamcha/maud/blob/54c466c681b5b7074efa815d393049601e358e96/static/src/coffee/posts.coffee#L94)) se non va cambiato "typeof == 'object'" in "instanceof HTMLElement" come in editPost

**Comment by silverweed** [comment]
Risolto con 5dfe75acd44f8e48caa414e3db306602861dd588 anche l'hack di Coffeescript.
