### ISSUE TITLE
BBCode/MD guide

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#31]
Richiesta dalla radice piu\` quadrata della contea e decisamente non l'unica a trarne beneficio.
Una miniguida sui BBCode/MD che sia possibilmente aggiornata alle ultime modifiche.

Decisioni da fare:
- Dove metterla? Pensavo ad un tastino nella zona "New Thread"/"Reply".
- Apre un popup o cosa? Odio i popup, ma sarebbe la soluzione piu\` pulita e facilmente espandibile

**Comment by Hamcha** [comment]
Messa pagina nella wiki, considerare se spostarla su una pagina di Maud dedicata

**Comment by silverweed** [comment]
Magari aggiungiamo un bottoncino "?" a fianco agli altri che redirige qui alla wiki...

**Comment by Hamcha** [comment]
Grandissima idea (magari dall'altro lato) ma lo vorrei comunque fare dentro crunchy. Github wiki non ama il mobile.

**Comment by Hamcha** [comment]
Aggiunto in 98f6175

**Comment by silverweed** [comment]
Mi piace la soluzione!
