### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#36]
Cercare di rendere thumbnail il più possibile da light mode

Derpibooru e imgur sono abbastanza semplici.

Extra: Valutare se renderlo una lib esterna (magari becchiamo contributore)

**Comment by silverweed** [comment]
Per imgur se vuoi faccio io, credo sia molto semplice [data la documentazione](https://api.imgur.com/models/image)...una cosa: preferisci thumbnail piccolo (160x160) o medio (320x320)? O altro?

**Comment by Hamcha** [comment]
Lightify stub be1f41e

**Comment by silverweed** [comment]
Stavo pensando: non sarebbe sensato thumbnailizzare il thumbnailizzabile anche in non-light mode (visto che comunque resizziamo le immagini)?

**Comment by Hamcha** [comment]
Da 574b61e viene thumbato tutto anche in full mode!
