### ISSUE TITLE
Refactoring..?

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#39]
Vorrei separare in piu moduli maud, avere un main che e' main.go, handlers.go etc. e mettere sottomoduli tipo parsers, databases etc.
Il vantaggio sarebbe poter avere tutto piu modulare e sostituibile (ie. alternative a mongo come backend database / piu parser pluggabili che seguono una interfaccia unica, etc.).

Si fa?

ping @silverweed

**Comment by silverweed** [comment]
Approvo, la "fatica" da fare è di certo ripagata dai vantaggi :+1
