### ISSUE TITLE
Bbcode editor selection bug

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#41]
La modifica di @silverweed per inserire i tag dove sta il cursore ignora che ci possa essere del testo selezionato, in tal caso i tag andrebbero messi attorno.

**Comment by silverweed** [comment]
Vero, provvedo a fixare e aggiungo alla #40 (o sta diventando troppo grossa come PR?)

**Comment by silverweed** [comment]
Fatto https://github.com/silverweed/maud/commit/2e5c462e58a484e4ad932b4b0de28e33d92c7d24

**Comment by Hamcha** [comment]
Mergata #40
