### ISSUE TITLE
Pretty error pages

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#42]
Al momento abbiamo 404 e 500, ma ci sono ancora punti in cui la pagina di errore è una semplice scritta (Invalid tripcode, ad esempio). Il wrapper già c'è, manca fare le pagine.

**Comment by silverweed** [comment]
Alrighty! In sostanza c'è solo da fare le immagini e usare sendError al posto di http.Error, giusto?

**Comment by Hamcha** [comment]
E jojo references! E' una delle regole non scritte!

**Comment by silverweed** [comment]
Forse dovrei iniziare a guardarlo...:P

**Comment by Hamcha** [comment]
403 e 401 pronte! chiudo
