### ISSUE TITLE
Strip hashtag URL character

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#45]
tipo i tag di [questo thread](https://crunchy.rocks/thread/ag/page/1#p0)

Porta a https://crunchy.rocks/tag/mu/, quando dovrebbe portare a https://crunchy.rocks/tag/mu

**Comment by silverweed** [comment]
Proporrei di renderli proprio illegali, visto che poi potrebbero cozzare con tag omonime:
`#/musica/  redirects to /tag/musica`
`#musica redirects to /tag/musica`

**Comment by Hamcha** [comment]
Se riesci a sanitizzarli sei un grande, ma mi starebbe benissimo renderli illegali

**Comment by silverweed** [comment]
Vedi #47

**Comment by Hamcha** [comment]
Sistemati gli URL nelle altre pagine non coperte da #47, chiudo
