### ISSUE TITLE
URLs are escaped incorrectly

### ISSUE THREAD

**Issue by silverweed** [Hamcha/maud#48]
Come dimostra [questo post](https://crunchy.rocks/thread/bg/page/1#p4), c'e' qualcosa che non va nel bbcode [url]: i caratteri '?' e '=' non dovrebbero essere covertiti in html entities, ma rimanere tali.
Lo fixerei io (in teoria basta modificare [queste righe](https://github.com/Hamcha/maud/blob/master/src/bbcode.go#L36-L39), oppure levarle del tutto), ma al momento non posso fare test ne` collegarmi a interceptor.

**Comment by Hamcha** [comment]
Quel codice [l'avevi inserito tu](https://github.com/Hamcha/maud/commit/684a185740e81827097702770b8d885f01e3846a), ti ricordi mica perche\`?

Ho un'altra soluzione in mente, vedo se risolve.

**Comment by silverweed** [comment]
Vedi #50

**Comment by Hamcha** [comment]
Fixata con 8183885
