### ISSUE TITLE
Anon edit

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#49]
Ho notato che alcuni anon doppiopostano per rimediare errori, magari sarebbe utile tenere una sorta di hidden-tripcode a tempo di post per edit/delete.

L'idea implementativa e' questa:

Se posto come anon, genera hidden tripcode e salvalo in LocalStorage, assieme all'id del thread e numero del post.
Quando poi visito il thread, se ho idthread/idpost settati, mostro quel post come editabile, ed ad edit time il browser usa l'hidden tripcode.
Tutto nascosto dall'utente, e viene sovrascritto appena fa un altro post altrove.

@silverweed ti sembra fattibile/sensato/ne vale la pena?

**Comment by silverweed** [comment]
Sì, direi che è una buona idea; l'unica è fare in modo che qualche utente particolarmente haxx0rzz non si metta a editare post altrui a caso (magari mettere anche un timelimit all'hidden tripcode, che so, 30 minuti o un'ora).

**Comment by Hamcha** [comment]
Mergata, chiudo
