### ISSUE TITLE
Peso delle immagini in light mode

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#53]
Per quanto sia comodo avere il "clicca per aprire" in light mode non è molto chiaro quanto possa una singola immagine impattare.

Sarebbe figo fare delle richieste HEAD (quindi solo header, niente contenuto) alle immagini "censoorate" (come direbbe il doc) per vedere quando sono pesanti (basato sul Content-Length)

I problemi sarebbero un calo di sicurezza mostruoso (ie. se uno fa un post con tremila link trasforma il nostro sito in una macchina per DoS) e, volendo evitare quest'ultimo, dover usare storage per tenerci in memoria quanto pesa ogni immagine.

@silverweed hai mica idee su come potremmo fare?

**Comment by silverweed** [comment]
Non saprei...quali sarebbero i vantaggi? Filtrare solo le immagini che pesano più di tot oppure filtrarne dopo che una pagina supera un tot peso o ancora filtrarle tutte e mettere un'indicazione sulle dimensioni accanto al "clicca per aprire"?

**Comment by Hamcha** [comment]
Generalmente far distinguere tra l'immagine idiota da 3kb e la uberGIF da 10MB.

**Comment by silverweed** [comment]
Capito; ci può stare, ma come pensavi di salvare i metadati? Su mongo o da qualche altra parte?

**Comment by silverweed** [comment]
Aggiungo che, se dedicassimo una collection del db per tenerci in memoria i metadati, volendo potremmo anche risolvere i titoli dei video youtube linkati durante il POST (usando l'API di YT o altro).

**Comment by silverweed** [comment]
A quanto ho capito questo è un "wontfix", visti i problemi di sicurezza intrinseci...è il caso di chiudere?

**Comment by Hamcha** [comment]
Per ora, perlomeno, sì.

Non me la sento atm di dedicare risorse per post anonimi o quasi. Magari in futuro via servizi esterni? (Pensa Embedly) Bisognerebbe vedere costi tho
