### ISSUE TITLE
Empty tags

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#54]
Dalla pagina di edit non vengono filtrati tag vuoti.

~~Extra: cancellare il tag vuoto generato su /cr/~~ fatto da @silverweed

**Comment by silverweed** [comment]
Facendo delle prove mi sembra che questo bug non esista più, visto che ora l'api rigetta automaticamente le tag vuote. Testato sia con l'UI che con curl.

**Comment by Hamcha** [comment]
Confermo, chiudo
