### ISSUE TITLE
Quote button

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#57]
DarkFear chiedeva se si potesse mettere un qualcosa per quotare direttamente dal post.

Vedo piu' o meno due modi (anche un po ed un po) di fare la cosa:
**Modo forum:** Tastino "Quote" che copia il messaggio e lo precede da >
**Modo imgboard:** Il numero del post diventa cliccabile ed aggiunge un ">> #numero" che diventa cliccabile e porta al post specificato

**Comment by silverweed** [comment]
Mi sembrano entrambe fattibili; io inizierei con il modo 2 che non richiede cambiamenti nell'UI ed è semplice da attuare; per il modo 1 per ora uno può fare copy-paste + maudtext button d'altronde (certo, da mobile è sbatta, ma nulla impedisce che poi implementiamo anche il modo 1)

**Comment by Hamcha** [comment]
Mergata #58 
Per altri miglioramenti (ie. floating box) apriamo altre issue
