### ISSUE TITLE
JS-free

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#59]
Un trend che sta prendendo un sacco ultimamente e' rendere i propri siti utilizzabii anche senza javascript (implicando funzionalita' ridotte, ma che sia comunque utilizzabile).. non sarebbe neanche una cattiva idea.

Con il mio ultimo commit (5c0bbec) ho messo una sorta di fallback per le date, specie visto che @silverweed ha notato che su Safari (iPad 1) non venivano proprio gestite.

Se si trova il tempo per fare altri fallback, ben venga, per quanto non sia un requisito o roba ad alta priorita'.

Manca ancora di fallback:
  - ~~Edit/Delete (magari una pagina a parte aka PHPBB, con tanto di editor allo stesso modo?)~~
  - ~~Pulsanti dell'editor (potremmo disabilitarli se JS e' off)~~
  - ~~\[Click to view image\] (potremmo mettere link _blank se JS e' off)~~
  - ~~Pulsante tag search~~
  - ~~Lista delle pagine~~

**Comment by silverweed** [comment]
Sembra una buona idea, direi che vale la pena fare almeno un po' di queste cose un po' per volta. (Scusa se in questi giorni non mi sono fatto sentire ma ho avuto l'influenza e la febbre alta; appena mi rimetto per bene torno su IRC :D)

**Comment by silverweed** [comment]
Vedi #77

**Comment by silverweed** [comment]
Vedi #78

**Comment by Hamcha** [comment]
Credo che con questo possiamo chiudere questa issue.

A quando il kickstarter per farti una statua?
