### ISSUE TITLE
Captcha contro i mutui su /cr/

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#65]
Payday loans ha rotto il cazzo, quasi quanto DT (quasi!)

Sarebbe il caso di mettere una sorta di captcha idiota, anche una domanda stupida, per gli ip esteri su /cr/.

**Comment by silverweed** [comment]
Dici che possiamo fare un modulo dedicato? magari da inserire in apiReply...

**Comment by silverweed** [comment]
Vedi #67
