### ISSUE TITLE
Remember seen threads

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#72]
Sarebbe figo se navigando home e lista thread si potesse sapere quali thread NON sono stati aggiornati dopo l'ultima visita (al thread).

Si potrebbe fare embeddando un id in giro per il thread (e nella last reply della threadlist) e tenendone traccia in LocalStorage.

Abbiamo diritto a 5MB di LocalStorage, quindi volendo lo terrei anche corto (e non possiamo usare il numero per le solite ragioni).

Idea: teniamo parte dell'id di mongo hashizzato (come succede per i tripcode, ma con un hashing piu' veloce e non crittografico) e lo salviamo in localStorage quando uno legge l'ultimo post di un thread.

**Comment by silverweed** [comment]
Bella idea, approvo. Visto che hai gia` robe da fare se vuoi ci penso io.

**Comment by silverweed** [comment]
Vedi https://github.com/Hamcha/maud/commit/88131a1b7584fbf434c2cb8736995e89e186d495 e seguenti
