### ISSUE TITLE
Post preview on hover

### ISSUE THREAD

**Issue by silverweed** [Hamcha/maud#74]
Prima o poi sarebbe carino fare un improvement al post quote by id `>> #1` rendendolo simile a quello che fa 4chan. Attualmente abbiamo il link al post (a cui pensa `maudtext.go`) e l'highlighting del post citato on hover (fatto da `fixes.coffee`).

Mancherebbe fare la verifica se il post citato è dentro il viewport o meno e, in caso contrario, farlo apparire on hover invece di fare l'highlighting.

**Comment by Hamcha** [comment]
:+1: 
Un div position absolute appena sopra il testo potrebbe bastare?
