### ISSUE TITLE
Forced Anon (client-side)

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#76]
E' spuntata una richiesta per una feature client-side (via Site Options)
L'opzione nasconderebbe tutti i nomi/trip rimpiazzandoli con anon (Rock/Boulder/etc).
Non dovrebbe essere complicato da fare, magari un po' lunghetto, e terrebbe a bada [sta gentaglia](https://crunchy.rocks/thread/ngE/page/3#p76)

@silverweed, che ne dici?

**Comment by silverweed** [comment]
Ok, dovrebbe essere una roba rapida e indolore da fare. Dovrei avere tempo adesso di implementarla.

**Comment by Hamcha** [comment]
Fatta, Committata, Mergata e Remaudata da @silverweed
