### ISSUE TITLE
Using Imgur's GIFV

### ISSUE THREAD

**Issue by silverweed** [Hamcha/maud#79]
Imgur ha introdotto una [feature interessante](http://imgur.com/blog/2014/10/09/introducing-gifv/comment-page-1/) qualche tempo fa: ogni Gif uploadata al sito viene convertita automaticamente in formato webm/mp4 e, oltre all'URL della Gif convenzionale, viene creato un URL con cui accedi alla Gif in formato video. In altre parole, se ho una `http://i.imgur.com/my-gif.gif`, avrò anche (se l'upload è abbastanza recente) una `http://i.imgur.com/my-gif.gifv` con la pic in formato webm. Ovviamente quest'ultima è molto più leggera dell'originale, di quasi 2 ordini di grandezza tipicamente.

Potremmo usare questa cosa su maud? Del tipo, riconoscere le gif provenienti da imgur e convertirle in `<video src="http://i.imgur.com/my-gif.webm" autoplay loop muted>`? 

Al contrario, è possibile usare questa cosa in light mode per inserire un thumbnail al posto del link `[embedded video]`, visto che le gifv hanno sempre il thumbnail di Imgur allo stesso link con la 'm' in fondo all'ID, per cui si potrebbe convertire, per dire:  
`[video]http://i.imgur.com/my-webm.webm[/video]`  
in  
`<a href='http://i.imgur.com/my-webm.webm'><img src='http://i.imgur.com/my-webmm.gifv'/></a>`

**Comment by Hamcha** [comment]
:+1:

**Comment by silverweed** [comment]
Potremmo fare qualche prova euristica...caricando una Gif totalmente arrandom senza specificare niente ho appena visto che me la converte, quindi è probabile che sia una feature attiva automaticamente a partire dall'Ottobre 2014...chiaro che le gif più vecchie non hanno questa cosa, e non saprei come fare per riconoscerle.

**Comment by silverweed** [comment]
Vedi https://github.com/Hamcha/maud/commit/5490b651e440ae7641c6a1ff8705167ae764020f per la conversione webm->thumbnail

**Comment by silverweed** [comment]
Vedi 5e6515856685a39de2a87d3b741dc3c7c268e947 per la conversione gif -> webm.
