### ISSUE TITLE
Anti spam

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#80]
Woah l'attacco di oggi! 10+ Thread generati nel giro di un paio d'ore, e tutti di notte!

Sarebbe comodo trovare altre misure antispam, visto che gestire captcha manualmente non ci portera' molto lontano, specie quando non ci siamo io e @silverweed.

Prima di partire con le proposte antispam, propongo una feature:
~~API per bannare e ricaricare la banlist in automatico da maud. Oltre ad evitare di dover cambiare il file a mano e ricaricare (magari da mobile non e' comodo) l'autoban tornerebbe utile per alcune delle proposte.~~ Vedi #81 

Cosa non fare:
- Rate limiting.. magari come antiflood, ma antispam non funziona, i vari thread di oggi erano a tipo 20 minuti l'un dall'altro.
- Word filtering - ClALlS, nuff said.
- ReCaptcha - Ma l'hai visto? Besides poi avrei porte aperte per farmi cagare il cazzo coi cookie.

Proposte antispam:
- ~~[This](http://urbanoalvarez.es/blog/2008/08/23/best-unobtrusive-anti-spam-technique-not-captcha/), i bot antispam mettono merda ovunque, mettere quindi field invisibili, magari lasciando name/id strani (generati casualmente per evitare autofill) e solo il placeholder con "do not fill", e rifiutare chiunque lo riempia (magari con captcha automatico).~~ 4ecfb61
- DNSBL, un sacco di ip di spammoni sono probabilmente gia in molte blacklist, ma mi sta troppo sul culo dare gli ip di chi posta ad una DNSBL.
- ~~Country filtering - Un po' quello che facciamo gia con la blacklist, facciamo un geoip check (bastano i primi 3 campi dell'ip) per sapere la zona del poster e captchamo in automatico per "zone difficili" ie. Ucraina/Russia/Cina.~~ c8f1ee5

Immagino si possa usare una combinazione delle 3 (se field riempito/fuori dall'italia -> controlla DNSBL -> ban automatico se esiste) ma ci porteremmo dietro i problemi di ogni singolo approccio.

Ping @silverweed

**Comment by Jhyrachy** [comment]
Inserimento di Captcha-Pony per IP non italiani.

Esempio:
Completa il nome: 
Rainbow _______
Twilight _______
Pinkie _____
Apple____
Flutter___

Di chi é la bestiola?
Tank → ______
Winona → _______

Etc

**Comment by silverweed** [comment]
La soluzione dei campi do not fill e l'auto captcha per geoip mi piacciono, inizierei con quelle per poi fare (o anche in parallelo) l'API per il ban non manuale.
@jhyrachy il captcha che abbiamo attualmente più o meno è già così, resta solo da attivare in automatico.

**Comment by silverweed** [comment]
Vedi #81

**Comment by Hamcha** [comment]
#81 mergata

Visto che le ultime misure sono piu antiflood che antispam, chiudo e nel caso riapriamo.
