### ISSUE TITLE
Ignore bans when in AdminCP

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#83]
Qualche giorno fa ho bannato il mondo intero per una svista e non potevo rimuovere il ban dall'adminCP (e non avevo accesso diretto al server).

Considerando che l'accesso all'admincp è gia ristretto, sarebbe comodo fargli ignorare i ban.

**Comment by silverweed** [comment]
Approvo.

**Comment by silverweed** [comment]
Vedi 8cfa4a7dd9a2e52737bf7be1cc2103365ffe7020
