### ISSUE TITLE
SSL Proxy

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#84]
Proxy SSL per risorse esterne (immagini / webm)

TODO:
- [x] Download e retrieve di risorse arbitrarie
- [x] Integrazione via formatter
- [x] Rimozione di contenuti vecchi (via cronjob)

EXTRA:
- [x] Pulizia se si supera una soglia massima di spazio
- [x] Pre-scaling delle immagini nel thread (per evitare reflow continui durante il caricamento)
- [ ] Info sulle immagini (dimensione) in Light mode
- [x] Client-side opt-in (opt-out?) via cookie
- [ ] Limite immagini per evitare DOS

**Comment by silverweed** [comment]
^ non si possono assignare più persone?

**Comment by Hamcha** [comment]
Nope, Github is love github is life.

**Comment by silverweed** [comment]
cronjob: vedi [marble](/silverweed/marble)

**Comment by Hamcha** [comment]
Ok, segnato completato tutto ciò che riguardava marble.. per me possiamo mergare così com'è..

**Comment by silverweed** [comment]
:+1: ok
