### ISSUE TITLE
some error pages look bad from mobile

### ISSUE THREAD

**Issue by silverweed** [Hamcha/maud#89]
Ad esempio la 404 sul mio WP ha il titolo che esce dall'header; le altre pagine non le ho ancora verificate, ma probabilmente hanno problemi analoghi.

**Comment by silverweed** [comment]
[404](https://little.crunchy.rocks/404)
[403](https://little.crunchy.rocks/static/)
[401](https://little.crunchy.rocks/thread/6gI/post/7/edit) (postando con un trip a caso)

**Comment by silverweed** [comment]
Piu` o meno fixato qui https://github.com/Hamcha/maud/commit/3ddcc0b023d6e8c2e07adafb7bfa29034d42f4a1

Tengo aperto nel caso vuoi dire qualcosa, altrimenti chiudi pure.

**Comment by Hamcha** [comment]
LGTM
