### ISSUE TITLE
Add one or more checks for proxied content

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#91]
https://crunchy.rocks/thread/ngI/page/2#p37

**Comment by silverweed** [comment]
Difficilmente riproducibile, probabilmente un derp del network in quel momento (riscaricare la stessa GIF ha funzionato in un secondo tempo...)

**Comment by Hamcha** [comment]
Sarebbe comunque da aggiungere un check, anche solo della dimensione, per essere sicuri che i contenuti scaricati siano effettivamente integri

**Comment by silverweed** [comment]
:+1: Approved, non dovrebbe essere particolarmente arduo

**Comment by silverweed** [comment]
Vedi #93
