### ISSUE TITLE
Add Post # to each post

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#92]
Contare quanti post abbiamo ad ogni apiReply è brutale, plus un Post# trivializza il problema del redirezionare alla giusta pagina in fulltext search.

- [x] Aggiungere il "numero di post" ad ogni post
- [x] Ricalcolo del post # dopo un Purge
- [x] Cambiare i PostCount con un "prendi il post# del messaggio precedente ed aggiungi uno"
- [x] Fare uno script che migra al nuovo formato i dati esistenti

..altro?

Mi ci metto volentieri io, ma prima voglio finire CSP.

**Comment by silverweed** [comment]
Mi piacerebbe fare qualcosa ma non posso garantire di avere gran tempo libero. Inizio a lavorarci, poi vedo se mi viene in tempi ragionevoli.

**Comment by silverweed** [comment]
Fatto, vedi #94.
