### ISSUE TITLE
Get rid of Google Fonts

### ISSUE THREAD

**Issue by Hamcha** [Hamcha/maud#95]
Avere Google che ci spia è BBBBBRUTTO.

**Comment by silverweed** [comment]
Cosa proponi? (I font non si possono scaricare e tenere in locale?)

**Comment by Hamcha** [comment]
Si può, ma non c'ho sbatti oggi, magari domani faccio qualcosa :D

Il giorno mer 30 nov 2016 alle ore 20:11 Silverweed <
notifications@github.com> ha scritto:

**Comment by silverweed** [comment]
![](http://i.imgur.com/xgLP6NGm.png)

**Comment by silverweed** [comment]
Risolto da ea587ffa513158df9369880f4e7c654093874b3c

![waiting](https://media3.giphy.com/media/SD1Jtmhgipgpq/giphy.gif)
